/* Sample crux data — fictional cases for the UI kit recreation. */
window.CRUX_DATA = {
  cases: [
    {
      id: 'CASE-0148',
      title: 'Why is my 10K pace 20s/km slower than last spring?',
      stage: 3,
      verdict: 'progress',
      sharpened: 'Aerobic pace has regressed ~20s/km over 14 weeks despite stable mileage — find the single dominant cause before changing training.',
      notInvestigating: ['Shoe wear', 'GPS watch accuracy', 'Weather / heat'],
      plans: [
        { key: 'A', name: 'Chronic underfueling', standing: 0.62, state: 'leading', prior: 0.62,
          mechanism: 'Sustained energy deficit suppresses thyroid output and blunts training adaptation.',
          sources: [
            { kind: 'book', label: 'Noakes — Lore of Running' },
            { kind: 'article', label: 'RED-S consensus 2023', href: '#' },
            { kind: 'youtube', label: 'CritFit · Fueling for endurance', href: '#' },
          ] },
        { key: 'B', name: 'No deload in 14 weeks', standing: 0.30, prior: 0.30,
          mechanism: 'Accumulated fatigue without a recovery week masks fitness as flat pace.',
          sources: [ { kind: 'article', label: 'Supercompensation review', href: '#' } ] },
        { key: 'C', name: 'Low ferritin / iron', standing: 0.12, state: 'ruled-out', prior: 0.12,
          mechanism: 'Iron deficiency limits oxygen transport and aerobic ceiling.',
          sources: [ { kind: 'article', label: 'Iron status in endurance athletes', href: '#' } ] },
      ],
      probe: { type: 'lab-test', targetMetric: 'ferritin > 30 ng/mL', status: 'designed', cost: '$40', time: '3 days',
        note: 'Order a ferritin + iron panel — see a doctor. crux does not run this probe.' },
      verdictLog: null,
    },
    {
      id: 'CASE-0147',
      title: 'Why do I blurt over people in meetings?',
      stage: 4,
      verdict: 'awaiting',
      sharpened: 'Interrupting spikes in fast-paced meetings — isolate whether it is anxiety-driven or a habit loop before any fix.',
      notInvestigating: ['1:1 conversations', 'Written comms'],
      plans: [
        { key: 'A', name: 'Anticipatory anxiety', standing: 0.48, state: 'leading', prior: 0.48,
          mechanism: 'Fear of forgetting the point triggers an early interrupt.',
          sources: [ { kind: 'book', label: 'Atomic Habits' } ] },
        { key: 'B', name: 'Pure habit loop', standing: 0.40, prior: 0.40,
          mechanism: 'Reinforced reward (being heard) cements the interrupt cue.',
          sources: [ { kind: 'youtube', label: 'Huberman · habit formation', href: '#' } ] },
        { key: 'C', name: 'Pace mismatch', standing: 0.12, prior: 0.12,
          mechanism: 'Slow-processing meetings feel like dead air to fill.',
          sources: [] },
      ],
      probe: { type: 'behaviour-experiment', targetMetric: 'blurt-rate ↓ 50%', status: 'running', cost: 'free', time: '2 weeks',
        note: 'Tally each interrupt in a notes app for 10 meetings; compare weeks 1 vs 2.' },
      verdictLog: null,
    },
    {
      id: 'CASE-0142',
      title: 'Should perf-coach send weekly digests by email or push?',
      stage: 5,
      verdict: 'confirmed',
      sharpened: 'Decide the digest channel that maximises weekly active return without raising unsubscribes.',
      notInvestigating: ['Digest content', 'Send time'],
      plans: [
        { key: 'A', name: 'Email digest', standing: 1.0, state: 'won', prior: 0.55,
          mechanism: 'Email tolerates long-form recap and is checked deliberately.',
          sources: [ { kind: 'article', label: 'Retention by channel benchmark', href: '#' } ] },
        { key: 'B', name: 'Push notification', standing: 0.35, state: 'ruled-out', prior: 0.45,
          mechanism: 'Push has higher open but worse depth and more opt-outs.',
          sources: [ { kind: 'article', label: 'Push fatigue study', href: '#' } ] },
      ],
      probe: { type: 'prototype', targetMetric: 'WAU return +8%', status: 'confirmed', cost: '1 sprint', time: '2 weeks',
        note: 'A/B the two channels behind a flag for two weeks.' },
      verdictLog: { outcome: 'confirmed', notes: 'Email lifted WAU return by 11% with flat unsubscribes. Shipping email digest.', decidedAt: '2569-05-30' },
      actionPlan: { planKey: 'A', name: 'Ship weekly email digest', mechanism: 'Roll email digest to 100%; revisit push only for time-critical alerts.' },
    },
    {
      id: 'CASE-0139',
      title: 'Is my afternoon energy crash caused by lunch carbs?',
      stage: 5,
      verdict: 'killed',
      sharpened: 'Test whether high-GI lunches cause the 2pm crash, before restructuring meals.',
      notInvestigating: ['Caffeine timing', 'Sleep debt'],
      plans: [
        { key: 'A', name: 'High-GI lunch spike', standing: 0.30, state: 'ruled-out', prior: 0.6,
          mechanism: 'Glucose spike then reactive dip drives drowsiness.',
          sources: [ { kind: 'youtube', label: 'Glucose Goddess', href: '#' } ] },
        { key: 'B', name: 'Post-lunch circadian dip', standing: 0.70, state: 'won', prior: 0.4,
          mechanism: 'Natural post-prandial circadian trough, independent of carbs.',
          sources: [ { kind: 'book', label: 'Why We Sleep' } ] },
      ],
      probe: { type: 'measurement', targetMetric: 'CGM Δ < 30 mg/dL', status: 'killed', cost: '$80', time: '1 week',
        note: 'Wear a CGM; compare low- vs high-carb lunches across 7 days.' },
      verdictLog: { outcome: 'killed', notes: 'Crash persisted on low-carb days. Carbs are not the cause — it is the circadian dip. Plan A killed.', decidedAt: '2569-05-12' },
      actionPlan: { planKey: 'B', name: 'Schedule deep work before noon', mechanism: 'Move demanding work to mornings; accept a lighter 2–3pm block.' },
    },
  ],
  projects: [
    { id: 'commander', name: 'commander', accent: 'var(--blue)' },
    { id: 'perf-coach', name: 'perf-coach', accent: 'var(--green)' },
    { id: 'crux', name: 'crux', accent: 'var(--crux)', active: true },
  ],
};
