services:
  - type: web
    name: crux
    env: python
    region: singapore
    branch: develop
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ENV
        value: production
      - key: PYTHON_VERSION
        value: "3.12.0"
      - key: AUTH_SECRET
        sync: false
